// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tisjohgybvntovgogkij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpc2pvaGd5YnZudG92Z29na2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzE2OTMsImV4cCI6MjA2MDEwNzY5M30.kKDWb15-U3HXlqapLCz5yxyMBXlEmRf1CsiSl_T_Pe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);