
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tisjohgybvntovgogkij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpc2pvaGd5YnZudG92Z29na2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzE2OTMsImV4cCI6MjA2MDEwNzY5M30.kKDWb15-U3HXlqapLCz5yxyMBXlEmRf1CsiSl_T_Pe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define custom types to use in our application
export interface UserItinerary {
  id: string;
  title: string;
  days: number;
  start_date: string | null;
  pace: string | null;
  budget: string | null;
  interests: string[] | null;
  transportation: string | null;
  include_food: boolean | null;
  created_at: string;
  updated_at: string;
  user_id: string;
}

export interface ItineraryActivity {
  id: string;
  itinerary_id: string;
  day: number;
  time: string;
  title: string;
  location: string;
  description: string | null;
  image: string | null; // Changed from required to allow null
  category: string | null;
  created_at: string;
}
